version: '4.22.1'

services:
  php7.1:
    image: php:7.1.3-fpm
    build: 
      context: ./docker/php7.1
    hostname: php7.1
    ports:
      - "10001:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7.1/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend  
  php7.3:
    image: php:7.3-fpm
    build: 
      context: ./docker/php7.3
    hostname: php7.3
    ports:
      - "10002:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7.3/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend  
  php7.4:
    image: php:7.4-fpm
    build: 
      context: ./docker/php7.4
    hostname: php7.4
    ports:
      - "10003:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php7.4/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php7.4/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend     
  php8.1:
    image: php:8.1.23-fpm
    build: 
      context: ./docker/php8.1
    hostname: php8.1
    ports:
      - "10004:9000"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/php8.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php8.1/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend     
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - "80:80"
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ./projects/:/var/www/html   
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf   
    depends_on:
      - php7.1
      - php7.3
      - php7.4
      - php8.1
    networks:
      - backend  
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes: 
      - ./docker/mysql_volumes:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root 
      PMA_PASSWORD: "12345678"
    depends_on:
      - mysql
    ports:
      - "8080:80"   
    networks:
      - backend
networks:
  backend:
     driver: bridge        

        